### PR TITLE
Allow app title to contain Unicode characters

### LINKED ISSUE #284: Buildozer.spec 's title of your application can not be a Chinese character
Port of https://github.com/kivy/kivy/issues/3683.

```python
# Android packaging done!
# APK 中-1.0.0-debug.apk available in the bin directory
Traceback (most recent call last):
  File "/usr/local/bin/buildozer", line 9, in <module>
    load_entry_point('buildozer==0.30', 'console_scripts', 'buildozer')()
  File "/Library/Python/2.7/site-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/Library/Python/2.7/site-packages/buildozer/__init__.py", line 987, in run_command
    self.target.run_commands(args)
  File "/Library/Python/2.7/site-packages/buildozer/target.py", line 85, in run_commands
    func(args)
  File "/Library/Python/2.7/site-packages/buildozer/target.py", line 97, in cmd_debug
    self.buildozer.build()
  File "/Library/Python/2.7/site-packages/buildozer/__init__.py", line 198, in build
    self.target.build_package()
  File "/Library/Python/2.7/site-packages/buildozer/targets/android.py", line 735, in build_package
    self.buildozer.state['android:latestapk'] = apk
  File "/Library/Python/2.7/site-packages/buildozer/jsonstore.py", line 33, in __setitem__
    self.sync()
  File "/Library/Python/2.7/site-packages/buildozer/jsonstore.py", line 55, in sync
    fd.write(unicode(dumps(self.data, ensure_ascii=False)))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 210, in encode
    return ''.join(chunks)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 1: ordinal not in range(128)
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/30604361-buildozer-spec-s-title-of-your-application-can-not-be-a-chinese-character?utm_campaign=plugin&utm_content=tracker%2F77123&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F77123&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by udiboy1209**
Fix #284

Currently only fixed target android, because the problem was only seen while building android.

### CODE REVIEW

**Comment by dessant** [comment]
Will it also work with py3?

**Comment by udiboy1209** [comment]
No @dessant `str.decode('utf-8')` wont work in py3. How would one implement a workaround? using `sys.version_info`?

**Comment by dessant** [comment]
Yes, `sys.version_info` can be used. Because these cases will be present in other places too, we should copy over the compat module from kivy (without the stuff related to clock).
https://github.com/kivy/kivy/blob/master/kivy/compat.py

In this case, you could do:
```python
conf_title = config.get('app', 'title')
if PY2:
    conf_title = conf_title.decode('utf-8')
```

**Comment by udiboy1209** [comment]
`compat.py` seems like the way to go, but it should be done in another PR. I'll open a feature request issue for now. Including the file is the easy part, but replacing aspects of the code to use `compat` will be tough :stuck_out_tongue_winking_eye:.

**Comment by Ling-yun-mu** [comment]
Why can't I solve this problem according to your modification

**Pull request merged**
