### PR TITLE
use HTTPS urls

### PR DESCRIPTION
**Pull request by obfusk**

### CODE REVIEW

**Comment by obfusk** [comment]
@AndreMiras @tshirtman

Most of those URLs -- e.g. in the README -- aren't very important.

But downloading e.g. `ant` and `kivy` over unencrypted http w/o checking e.g. a SHA256 checksum is pretty bad security practice nowadays.

**Review by tshirtman — APPROVED** [review]
Didn't test the updated instructions, but indeed it's important to switch to https as much as possible.

**Comment by obfusk** [comment]
I tested the HTTPS URLs to see if they work, though I did not check whether the result is identical.

This is why I added a `www.` prefix to the sphynx URLS, since the URL without the prefix doesn't work over HTTPS.

**Review by AndreMiras — APPROVED** [review]
LGTM

**Comment by obfusk** [comment]
Given the security implications and otherwise harmlessness of these changes may I suggest doing a point release that includes (only) these changes?

**Pull request merged**
