### PR TITLE
fix: show output of sdk update if auto_accept_license is false

### LINKED ISSUE #916: Accept license terms prompt is not visible
buildozer version: 0.39
python : 3.7

When log level is low or `--verbose` is false the license accept prompt is not visible in the shell, and it seems that the process is stuck. The last line is `# Installing/updating SDK platform tools if necessary`

When --verbose is added, the long license text becomes visible, but there is still no prompt in the end, asking for user input - you just have to guess that you have to type 'y' and hit enter.

related: #66 and #870

### PR DESCRIPTION
**Pull request by tshirtman**
untested, but should fix #916

### CODE REVIEW

**Comment by AndreMiras** [comment]
Good one, thanks.
I'm willing to test it before merge, but I can't find a way to revert my setup to status prior accepting license. And deleting the entire `~/.buildozer` directory feels a bit overkill :stuck_out_tongue:

**Comment by tshirtman** [comment]
I was actually testing it just now, and it seem to work :) i got the license displayed and i could confirm it manually.

**Comment by tshirtman** [comment]
ok, it does work :)

**Comment by tshirtman** [comment]
yay \o/

**Pull request merged**
