### PR TITLE
Handle buildozer.spec with unicode chars

### PR DESCRIPTION
**Pull request by guysoft**
Other wise you get a UnicodeEncodeError in python3.

### CODE REVIEW

**Comment by guysoft** [comment]
The reason this is needed, because of the line:
https://github.com/kivy/buildozer/blob/master/buildozer/default.spec#L65
```
author = © Copyright Info
```

**Comment by AndreMiras** [comment]
Thanks for the fix, that may fix https://github.com/kivy/buildozer/issues/782
Funny to see it pops only now. Also I'm not sure why I can't reproduce it myself :thinking:

**Comment by homdx** [comment]
@guysoft , thank you!

Log:
https://github.com/kivy/buildozer/issues/782#issuecomment-453915678

**Comment by hackalog** [comment]
Note for posterity. This caused a python2 regression. Fixed in https://github.com/kivy/buildozer/pull/799

**Pull request merged**
