### PR TITLE
display-cutout

### PR DESCRIPTION
**Pull request by kuzeyron**
This PR enables display-cutout functionality.

### CODE REVIEW

**Comment by kuzeyron** [comment]
Final changes.

**Comment by mmdmoa** [comment]
bro that's so cool, I am craving this feature for a long time now!

**Comment by mmdmoa** [comment]
by the way, what do you mean by enabling display-cutout functionality?
do you mean edge to edge display rendering?

**Comment by kuzeyron** [comment]
> by the way, what do you mean by enabling display-cutout functionality? do you mean edge to edge display rendering?

I think the answer is yes. Without this function Kivy doesn't render beyond the status-bar even when it's set to fullscreen so this gives you the option to render more on the display.

**Comment by mmdmoa** [comment]
> > by the way, what do you mean by enabling display-cutout functionality? do you mean edge to edge display rendering?
> 
> I think the answer is yes. Without this function Kivy doesn't render beyond the status-bar even when it's set to fullscreen so this gives you the option to render more on the display.

That's great, I'm so waiting for this feature to be out! thanks!

**Pull request closed without merging**
