### PR TITLE
Spelling

### PR DESCRIPTION
**Pull request by jsoref**
Generated by https://github.com/jsoref/spelling `f`; to maintain your repo, please consider `fchurn`

### CODE REVIEW

**Comment by tito** [comment]
Thanks for providing a such PR, however, please rework to not changes anything about the CHANGELOG.md. Theses are direct commit message, and is auto generated.

**Comment by jsoref** [comment]
@tito: done

**Comment by tito** [comment]
Thanks you!

**Comment by jsoref** [comment]
Just noticed you merged it into unicode_fix instead of master. I presume it'll eventually make its way over...

**Pull request merged**
