### PR TITLE
added few additional options for android p4a builds

### PR DESCRIPTION
**Pull request by vesellov**
A corresponding Pull Request in p4a is here: https://github.com/kivy/python-for-android/pull/2338

... and here: https://github.com/kivy/python-for-android/pull/2248

### CODE REVIEW

**Comment by vesellov** [comment]
corresponding P4A pull requests are already merged.. so this should be also fine to go on

**Review by akshayaurora — DISMISSED** [review]

**Comment by akshayaurora** [comment]
@vesellov apologies for not looking at this earlier.  Would you please rebase the pr on top of current Buildozer removing the conflicts.

**Review by akshayaurora — APPROVED** [review]

**Comment by akshayaurora** [comment]
@vesellov nice work,  thanks 👍

**Comment by vesellov** [comment]
Thank you. Happy to help. I love Kivy

**Pull request merged**
