### PR TITLE
Fix Py3 Incompatable str + bytes issue.

### PR DESCRIPTION
**Pull request by FeralBytes**
Found while using buildozer with py3 on old-toolchain as $ buildozer android debug

### CODE REVIEW

**Comment by FeralBytes** [comment]
Change was also tested and worked on my system.

**Comment by FeralBytes** [comment]
@matham fixes in accordance with your suggestion.

**Comment by matham** [comment]
Sorry for not being explicit, but you don't need the if statement. It should always have the `b` prefix. The reason it works in py2 without is that it's automatically bytes. But it won't hurt having the `b` prefix and will reduce the complexity as you don't need the if and line duplication.

**Comment by FeralBytes** [comment]
@matham Fixed as noted. Also tested and works.

**Comment by FeralBytes** [comment]
Sorry about the pep8 issue.

**Comment by matham** [comment]
It's ok. I just didn't want to ask for another fix :D

**Pull request merged**
