### PR TITLE
Fix missing requirements: sh package

### PR DESCRIPTION
**Pull request by homdx**
Pull request for fix missing requirements.

Build under docker, have error:

```
File buildozer.spec created, ready to customize!
Traceback (most recent call last):
  File "/home/user/.local/bin/buildozer", line 11, in <module>
# Check configuration tokens
    sys.exit(main())
  File "/home/user/.local/lib/python2.7/site-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/home/user/.local/lib/python2.7/site-packages/buildozer/__init__.py", line 1053, in run_command
    targets = [x[0] for x in self.targets()]
  File "/home/user/.local/lib/python2.7/site-packages/buildozer/__init__.py", line 945, in targets
    fromlist=['buildozer'])
  File "/home/user/.local/lib/python2.7/site-packages/buildozer/targets/android.py", line 28, in <module>
    import sh
ImportError: No module named sh
```

### CODE REVIEW

**Comment by AndreMiras** [comment]
Is it not already fixed in master via https://github.com/kivy/buildozer/commit/2be2d77ffa57f3576fe71a95eb810d69ce91dff3#diff-2eeaed663bd0d25b7e608891384b7298R50 ?

**Comment by homdx** [comment]
> Is it not already fixed in master via [2be2d77#diff-2eeaed663bd0d25b7e608891384b7298R50](https://github.com/kivy/buildozer/commit/2be2d77ffa57f3576fe71a95eb810d69ce91dff3#diff-2eeaed663bd0d25b7e608891384b7298R50) ?

Yes, but docker now not valid. Becouse buildozer setupped with docker : from pip:

log build docker
```
Step 18/22 : RUN pip install --user Cython==0.25.2 $BDOZER_REQ
 ---> Running in 5d56e061747c
Collecting Cython==0.25.2
  Downloading https://files.pythonhosted.org/packages/bb/d4/94ac2711755839a2eba6c95fee57f6a09d9e6d6e436a8271212d52d5a7a9/Cython-0.25.2-cp27-cp27mu-manylinux1_x86_64.whl (6.4MB)
Collecting buildozer
  Downloading https://files.pythonhosted.org/packages/6b/a6/8f2183d890ce03c28e7ab3966db6fee52fd9840a3f483d4440327a360a8e/buildozer-0.37-py2-none-any.whl (83kB)
Collecting pexpect (from buildozer)
  Downloading https://files.pythonhosted.org/packages/89/e6/b5a1de8b0cc4e07ca1b305a4fcc3f9806025c1b651ea302646341222f88b/pexpect-4.6.0-py2.py3-none-any.whl (57kB)
Collecting virtualenv (from buildozer)
  Downloading https://files.pythonhosted.org/packages/6a/d1/e0d142ce7b8a5c76adbfad01d853bca84c7c0240e35577498e20bc2ade7d/virtualenv-16.2.0-py2.py3-none-any.whl (1.9MB)
Collecting ptyprocess>=0.5 (from pexpect->buildozer)
  Downloading https://files.pythonhosted.org/packages/d1/29/605c2cc68a9992d18dada28206eeada56ea4bd07a239669da41674648b6f/ptyprocess-0.6.0-py2.py3-none-any.whl
Collecting setuptools>=18.0.0 (from virtualenv->buildozer)
  Downloading https://files.pythonhosted.org/packages/37/06/754589caf971b0d2d48f151c2586f62902d93dc908e2fd9b9b9f6aa3c9dd/setuptools-40.6.3-py2.py3-none-any.whl (573kB)
Installing collected packages: Cython, ptyprocess, pexpect, setuptools, virtualenv, buildozer
Successfully installed Cython-0.25.2 buildozer-0.37 pexpect-4.6.0 ptyprocess-0.6.0 setuptools-40.6.3 virtualenv-16.2.0
 ---> e17138e28300
Removing intermediate container 5d56e061747c
Step 19/22 : RUN cd /tmp/ && buildozer init && buildozer android adb -- version && cd -
 ---> Running in 1dca9553c9b6
File buildozer.spec created, ready to customize!
# Check configuration tokens
Traceback (most recent call last):
  File "/home/user/.local/bin/buildozer", line 11, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python2.7/site-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/home/user/.local/lib/python2.7/site-packages/buildozer/__init__.py", line 1053, in run_command
    targets = [x[0] for x in self.targets()]
  File "/home/user/.local/lib/python2.7/site-packages/buildozer/__init__.py", line 945, in targets
    fromlist=['buildozer'])
  File "/home/user/.local/lib/python2.7/site-packages/buildozer/targets/android.py", line 28, in <module>
    import sh
ImportError: No module named sh
The command '/bin/sh -c cd /tmp/ && buildozer init && buildozer android adb -- version && cd -' returned a non-zero code: 1
```

**Comment by homdx** [comment]
> Is it not already fixed in master via [2be2d77#diff-2eeaed663bd0d25b7e608891384b7298R50](https://github.com/kivy/buildozer/commit/2be2d77ffa57f3576fe71a95eb810d69ce91dff3#diff-2eeaed663bd0d25b7e608891384b7298R50) ?

Maybe buildozer in docker need setup from sources? Like this?
`RUN python setup.py install`

Very important question:
**Docker need** latest **master**? (build from sources)
**Or** usage **stable** buildozer, from **pip**?

**Comment by AndreMiras** [comment]
Yes depending on what purpose Docker serves here it should install buildozer from the source.
This should already possible with `docker build --tag=buildozer --build-arg git=true .` via 2be2d77ffa57f3576fe71a95eb810d69ce91dff3

**Comment by homdx** [comment]
@AndreMiras In README.tst (https://github.com/kivy/buildozer/blob/master/README.rst) absent instruction, how setup buildozer in docker from git:

> Yes depending on what purpose Docker serves here it should install buildozer from the source.
> This should already possible with `docker build --tag=buildozer --build-arg git=true .` via [2be2d77](https://github.com/kivy/buildozer/commit/2be2d77ffa57f3576fe71a95eb810d69ce91dff3)

**Pull request closed without merging**
