### PR TITLE
Add ci_mode to toggle download progress

### PR DESCRIPTION
**Pull request by mkg20001**
Ref #823

### CODE REVIEW

**Comment by AndreMiras** [comment]
Great work! Same comment as https://github.com/kivy/python-for-android/pull/1727#issuecomment-466819110 could you review/address? :pray:

**Comment by mkg20001** [comment]
Noticed that the unzip command still spams

screenshot

Would anybody mind looking into that?

**Comment by AndreMiras** [comment]
Merged thanks!
Regarding the extraction command I think it comes from here https://github.com/kivy/python-for-android/blob/6660b9e/pythonforandroid/recipe.py#L405 but I haven't verified yet.
Basically `tar -tf` the `-t` flag is the verbose part, see man page:
> List the contents of an archive.  Arguments are optional.  When given, they specify the names of the members to list.

But let's keep it for another story so I'm merging your PR which already is an improvement. Thanks for making a commit amend/squash by the way, I also like clean commit log :smile:

**Comment by mkg20001** [comment]
Could you merge https://github.com/kivy/python-for-android/pull/1727 as well, please?

**Comment by AndreMiras** [comment]
Yes but for https://github.com/kivy/python-for-android/pull/1727 to make sense we need the .travis.yml update as well, do you mind making the change to the PR? :pray:

**Pull request merged**
